services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Symfony\Component\Mailer\MailerInterface:
        class: Symfony\Component\Mailer\Mailer
        arguments:
            - !service
                class: Symfony\Component\Mailer\Transport\NullTransport
