version: '3.7'

services:
    nginx:
        image: automagistre/www-nginx:${DRONE_BUILD_NUMBER}
        networks:
            - default
            - ingress
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host:www.automagistre.ru,automagistre.ru"
                - "traefik.frontend.priority=5"
                - "traefik.frontend.redirect.regex=^(.*)://automagistre.ru(.*)"
                - "traefik.frontend.redirect.replacement=$$1://www.automagistre.ru$$2"
                - "traefik.port=80"
                - "traefik.protocol=http"
                - "traefik.backend.loadbalancer.method=drr"

    php-fpm:
        image: automagistre/www-app:${DRONE_BUILD_NUMBER}
        environment:
            APP_SECRET: ${APP_SECRET}
            GRAPHQL_URL: https://msk.automagistre.ru/api/www
            API_URL: https://msk.automagistre.ru/api/v1
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    memcached:
        image: memcached:1.5.20-alpine
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s

    old_site:
        image: grachev/swarm-nginx:12
        environment:
            NGINX_BACKEND_HOST: 176.100.244.45:80
        networks:
            - ingress
        deploy:
            mode: global
            endpoint_mode: dnsrr
            update_config:
                order: stop-first
                failure_action: rollback
                parallelism: 1
                delay: 5s
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host:www.old.automagistre.ru,old.automagistre.ru"
                - "traefik.frontend.priority=10"
                - "traefik.port=80"
                - "traefik.protocol=http"
                - "traefik.backend.loadbalancer.method=drr"

networks:
    ingress:
        external: true
        name: proxy
    default:
        driver: overlay
        name: www_am
    tenant:
        external: true
        name: tenant_msk
