version: '3.7'

services:
    nginx:
        image: automagistre/www-nginx:${DRONE_BUILD_NUMBER}
        networks:
            - default
            - traefik
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.automagistre-www.rule=Host(`www.automagistre.ru`, `automagistre.ru`)"
                - "traefik.http.routers.automagistre-www.entrypoints=websecure"
                - "traefik.http.routers.automagistre-www.priority=5"
                - "traefik.http.routers.automagistre-www.tls=true"
                - "traefik.http.routers.automagistre-www.tls.certresolver=leresolver"
                - "traefik.http.services.automagistre-www-service.loadbalancer.server.port=80"
                - "traefik.http.services.automagistre-www-service.loadbalancer.server.scheme=http"
                - "traefik.http.routers.automagistre-www.middlewares=automagistre-www-redirect-to-www"
                - "traefik.http.middlewares.automagistre-www-redirect-to-www.redirectregex.regex=^(.*)://automagistre.ru(.*)"
                - "traefik.http.middlewares.automagistre-www-redirect-to-www.redirectregex.replacement=$$1://www.automagistre.ru$$2"

    php-fpm:
        image: automagistre/www-php:${DRONE_BUILD_NUMBER}
        environment:
            APP_SECRET: ${APP_SECRET}
            SENTRY_DSN: ${SENTRY_DSN}
            SENTRY_DSN_BROWSER: ${SENTRY_DSN_BROWSER}
            GRAPHQL_URL: https://msk.automagistre.ru/api/www
            API_URL: https://msk.automagistre.ru/api/v1
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    memcached:
        image: memcached:1.6.9-alpine
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s

networks:
    traefik:
        external: true
        name: traefik
    default:
        driver: overlay
        name: www_am
    tenant:
        external: true
        name: tenant_msk
