version: '3.7'

services:
    nginx:
        image: nginx:1.17.5-alpine
        labels:
            ru.grachevko.dhu: 'www.automagistre.local'
        volumes:
            - ./public:/usr/local/app/public
            - ./etc/nginx.conf:/etc/nginx/nginx.conf

    node:
        image: automagistre/www-node:base
        command: /bin/true
        volumes:
            - ./:/usr/local/app
        user: ${UID}:${GID}

    app:
        image: automagistre/www-app:base
        networks:
            default:
                aliases:
                    - php-fpm
        volumes:
            - ./:/usr/local/app
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            MYSQL_PASSWORD: 'db'

    memcached:
        image: memcached:1.5.20-alpine
        labels:
            ru.grachevko.dhu: 'memcached.www.automagistre.local'
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s

    dockerhost:
        image: qoomon/docker-host:2.2.0
        cap_add:
            - NET_ADMIN
            - NET_RAW

networks:
    default:
        name: www_automagistre
