version: '3.7'

services:
  nginx:
    image: automagistre/www-nginx
    restart: always
    build:
      context: .
      target: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.automagistre-www.rule=Host(`www.automagistre.ru`, `automagistre.ru`)"
      - "traefik.http.routers.automagistre-www.entrypoints=websecure"
      - "traefik.http.routers.automagistre-www.priority=5"
      - "traefik.http.routers.automagistre-www.tls=true"
      - "traefik.http.routers.automagistre-www.tls.certresolver=leresolver"
      - "traefik.http.services.automagistre-www-service.loadbalancer.server.port=80"
      - "traefik.http.services.automagistre-www-service.loadbalancer.server.scheme=http"
      - "traefik.http.routers.automagistre-www.middlewares=automagistre-www-redirect-to-www"
      - "traefik.http.middlewares.automagistre-www-redirect-to-www.redirectregex.regex=^(.*)://automagistre.ru(.*)"
      - "traefik.http.middlewares.automagistre-www-redirect-to-www.redirectregex.replacement=$$1://www.automagistre.ru$$2"
    environment:
      PHP_FPM_HOST: php-fpm
    networks:
      - default
      - traefik

  php-fpm:
    image: automagistre/www-php
    restart: always
    build:
        context: .
        target: php
    environment:
      APP_SECRET: ${APP_SECRET}
      GRAPHQL_URL: https://crm.automagistre.ru/msk/api/www

  memcached:
    image: memcached:1.6.9-alpine
    restart: always
    healthcheck:
      test: nc -z 127.0.0.1 11211
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  traefik:
    external: true
    name: traefik
  default:
    name: www_automagistre
