_old_redirects:
    resource: 'routes/old_redirects.php'

_service_brand:
    resource: '../src/Service/Controller/Brand'
    type: annotation
    prefix: /service/{brand}
    requirements:
        brand: "nissan|toyota|infiniti|lexus"

_shop:
    resource: '../src/Shop/Controller'
    type: annotation
    name_prefix: shop_
    prefix: /shop

_blog:
    resource: '../src/Blog/Controller'
    type: annotation
_blogs:
    resource: '../templates/blog/articles'
    type: blog

_garage:
    resource: '../src/Garage/Controller'
    type: annotation
    name_prefix: garage_
    prefix: /garage

_switcher:
    resource: '../src/Service/Controller/SwitchController.php'
    type: annotation
