_old_redirects:
    resource: 'routes/old_redirects.php'

_service:
    resource: '../src/Controller/Service'
    type: annotation
    prefix: /service/{brand}
    requirements:
        brand: "nissan|toyota|infiniti|lexus"

_shop:
    resource: '../src/Controller/Shop'
    type: annotation
    name_prefix: shop_
    prefix: /shop

_blog:
    resource: '../src/Blog/Controller'
    type: annotation
_blogs:
    resource: '../templates/blog'
    type: blog

_garage:
    resource: '../src/Controller/GarageController.php'
    type: annotation
    name_prefix: garage_
    prefix: /garage

_switcher:
    resource: '../src/Controller/SwitchController.php'
    type: annotation
