parameters:
    locale: ru
    router.request_context.host:   www.automagistre.ru
    router.request_context.scheme: https

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src'

    App\Router\ListeningRouterDecorator:
        decorates: router

    App\Blog\Routing\BlogLoader:
        arguments:
            - '@Symfony\Component\HttpKernel\Config\FileLocator'
        tags:
            - { name: routing.loader }
